### PR TITLE
v0.1.5 - Fix for paths with white spaces

### PR DESCRIPTION
**Pull request by sbis04**
Fixed the issue with the input and output video **paths having white spaces**.

Fix: #9

### CODE REVIEW

**Comment by dwikresno** [comment]
thanks for your respond, if you don't mind I have a suggestion for additional feature maybe you can put a parameter on loadVideo() to condition if people wanna take video source from camera not only from gallery, Thanks

**Comment by sbis04** [comment]
Hi, @dwikresno thanks for your suggestion. I think you can use the **camera** plugin and just pass the output video path to the `loadVideo()` method to achieve that. But, yes it would be much more convenient to have it within this package so that you do not have to import an extra package for that.

Okay, I have added this to my list of upcoming features.

**Comment by sbis04** [comment]
@dwikresno I have updated the implementation of the `loadVideo()` method in v0.2.0

Now, you will need the pass the video file to the method. I believe this gives more flexibility as you can load the video file using the file system or from the camera within the app externally.
```dart
await _trimmer.loadVideo(videoFile: file);
```

**Comment by dwikresno** [comment]
okay, thank you so much @sbis04

**Pull request merged**
