### PR TITLE
Done a package bump up

### PR DESCRIPTION
**Pull request by lvlrSajjad**
And did changes in order to be compatible with the latest flutter version and the other packages.

### CODE REVIEW

**Comment by aswanthtpconnects** [comment]
is it available in the same version (0.3.5)?

**Comment by dlinx** [comment]
Any updates on this PR?

**Comment by ToluwaniO** [comment]
any update on this?

**Comment by sbis04** [comment]
Have already migrated the package to null safety, thanks for the contribution!

**Pull request closed without merging**
