### PR TITLE
Fixed video freezing at the starting or at the end, added videoBitRate Control…

### PR DESCRIPTION
**Pull request by philippaul1998**

### CODE REVIEW

**Comment by philippaul1998** [comment]
I found that the frame freezing issue occurred because of 

"-c copy"

and it happens only when one changes the starting position of the video.

So I removed it and added video bitrate control to retain video quality.

Hope this helps ☺️.

**Comment by sbis04** [comment]
This might have fixed the issue in theory. But this requires re-encoding the video with the specified bitrate. So, this will take a significantly greater amount of time. 

What `-c copy` does is, it omits the decoding and encoding step for the specified stream thus it is much faster.

Also, just for trimming a video re-encoding is completely unnecessary and time-consuming.

**Comment by philippaul1998** [comment]
Yeah, you are right. 
It takes long to process in this case. But it is the only way, I found to solve the issue.

By the way, the package is just awesome. 👏🏻

**Comment by leochiu-work** [comment]
> I found that the frame freezing issue occurred because of
> 
> "-c copy"
> 
> and it happens only when one changes the starting position of the video.
> 
> So I removed it and added video bitrate control to retain video quality.
> 
> Hope this helps ☺️.

Hi @98philips ,

How did you add video bitrate control to retain video quality ?

In v0.2.6, there's way to re-encode the video, but the quality becomes bad.

Thanks.

**Comment by 98philips** [comment]
> > I found that the frame freezing issue occurred because of
> > "-c copy"
> > and it happens only when one changes the starting position of the video.
> > So I removed it and added video bitrate control to retain video quality.
> > Hope this helps ☺️.
> 
> Hi @98philips ,
> 
> How did you add video bitrate control to retain video quality ?
> 
> In v0.2.6, there's way to re-encode the video, but the quality becomes bad.
> 
> Thanks.

Hi @leochiu-work ,

You can do that using FFmpeg command option as well, like `-b:v 2M`.

But I don't recommend this, although it improves video quality to some extent, the encoding is not that good.

For my case, what I did was to use libx264 to encode video, it's not available with this package so had to use flutter_ffmpeg package with at-least min-gpl (H.264 requires GPL License to use). Then I did the trimming and some compression with a custom ffmpeg command. 

`_flutterFFmpeg.execute( '-i $path -ss $s -t $d -c:v libx264 -preset ultrafast -crf 30 $outputPath');`

s -> start time (in seconds), 
d -> duration (in seconds).

Thanks.

**Pull request closed without merging**
